/*
 * Code generated by ObjectDomain using CPP Code Generator 2.0
 */

#include "GridBase.h"

/*
 * Latitude
 */
float GridBase::la(int i, int j) {
}

float GridBase::gi(float lo, float la) {
}

float GridBase::gj(float lo, float la) {
}

