/*
 * Code generated by ObjectDomain using CPP Code Generator 2.0
 */

#include <stdio.h>
#include "GridList.h"


GridList::GridList(GridBase* gb) 
{   
   gbase = gb;
//   fprintf(stderr, "Base %p\n", gbase);
}


void GridList::addData(GridData *data)
{   
   datalist.push_back(data);
}

GridData *GridList::getData(int i) 
{
   if (i < datalist.size())
     return datalist[i];
   else
     return 0;
}


int GridList::size() const {
   return datalist.size();
}


void GridList::setList(const char*filename)
{
	int i;
	float f;
	GridData *d = 0;
	FILE *in = fopen(filename, "r");

	if (in==NULL)
		return;
		
	while (!feof(in)) {
		if (d==0) {
			d = new GridData(gbase);
//	 addData(d);
			i = 0;
		}
		fscanf(in, "%g", &f);
//      fprintf(stderr, "%d:%g ", i, f);
		d->setData(i++, f);
		if (i==gbase->getN()) {
			addData(d);
			d = 0;
		}      
	}         	     
}


void GridList::writeData(const char *filename)
{
	FILE *out = fopen(filename, "wb");

	for(int i=0; i < size(); i++) {
		GridData *d = getData(i);
		d->writeData(out);
	}
	fclose(out);
}


void GridList::writeDataText(const char *filename)
{
	FILE *out = fopen(filename, "w");

	for(int i=0; i < size(); i++) {
		GridData *d = getData(i);
		d->writeDataText(out);
	}
	fclose(out);
}

