/*
 * Code generated by ObjectDomain using CPP Code Generator 2.0
 */

#include "GridData.h"
#include <vector>

using std::vector;

typedef vector<GridData*> datalist_type;


class GridList {

public:

	GridList(GridBase* gbase);

	void addData(GridData *data);

	GridData *getData(int i);


	void writeData(const char *);

	void writeDataText(const char *);

	void setList(const char*filename);

	int size() const;

private:

	datalist_type datalist;
	GridBase* gbase;

};
